export const FETCH_SUBJECTS_REQUEST =  'FETCH_SUBJECTS_REQUEST'
export const FETCH_SUBJECTS_SUCCESS =  'FETCH_SUBJECTS_SUCCESS'
export const FETCH_SUBJECTS_FAILURE =  'FETCH_SUBJECTS_FAILURE'

export const POST_SUBJECT_REQUEST =    'POST_SUBJECT_REQUEST'
export const POST_SUBJECT_SUCCESS =    'POST_SUBJECT_SUCCESS'
export const POST_SUBJECT_FAILURE =    'POST_SUBJECT_FAILURE'

export const UPDATE_SUBJECT_REQUEST =  'UPDATE_SUBJECT_REQUEST'
export const UPDATE_SUBJECT_SUCCESS =  'UPDATE_SUBJECT_SUCCESS'
export const UPDATE_SUBJECT_FAILURE =  'UPDATE_SUBJECT_FAILURE'

export const EDIT_SUBJECT = 'EDIT_SUBJECT'
export const SUBJECT_INFO = 'SUBJECT_INFO'

export const REMOVE_SUBJECT_REQUEST = 'REMOVE_SUBJECT_REQUEST'
export const REMOVE_SUBJECT_SUCCESS = 'REMOVE_SUBJECT_SUCCESS'
export const REMOVE_SUBJECT_FAILURE = 'REMOVE_SUBJECT_FAILURE'

