json.(
    @subject, 
        :id, 
        :title, 
        :level,
        :subject_category_id,
        :language_id,
        :passing_points,
        :notes, 
        :created_at, 
        :updated_at,
)