export const FETCH_SUBJECT_TESTS_REQUEST =  'FETCH_SUBJECT_TESTS_REQUEST'
export const FETCH_SUBJECT_TESTS_SUCCESS =  'FETCH_SUBJECT_TESTS_SUCCESS'
export const FETCH_SUBJECT_TESTS_FAILURE =  'FETCH_SUBJECT_TESTS_FAILURE'

export const POST_SUBJECT_TEST_REQUEST =    'POST_SUBJECT_TEST_REQUEST'
export const POST_SUBJECT_TEST_SUCCESS =    'POST_SUBJECT_TEST_SUCCESS'
export const POST_SUBJECT_TEST_FAILURE =    'POST_SUBJECT_TEST_FAILURE'

export const UPDATE_SUBJECT_TEST_REQUEST =  'UPDATE_SUBJECT_TEST_REQUEST'
export const UPDATE_SUBJECT_TEST_SUCCESS =  'UPDATE_SUBJECT_TEST_SUCCESS'
export const UPDATE_SUBJECT_TEST_FAILURE =  'UPDATE_SUBJECT_TEST_FAILURE'

export const EDIT_SUBJECT_TEST = 'EDIT_SUBJECT_TEST'
export const SUBJECT_TEST_INFO = 'SUBJECT_TEST_INFO'

export const REMOVE_SUBJECT_TEST_REQUEST = 'REMOVE_SUBJECT_TEST_REQUEST'
export const REMOVE_SUBJECT_TEST_SUCCESS = 'REMOVE_SUBJECT_TEST_SUCCESS'
export const REMOVE_SUBJECT_TEST_FAILURE = 'REMOVE_SUBJECT_TEST_FAILURE'

