export const FETCH_SUBJECT_CATEGORIES_REQUEST =  'FETCH_SUBJECT_CATEGORIES_REQUEST'
export const FETCH_SUBJECT_CATEGORIES_SUCCESS =  'FETCH_SUBJECT_CATEGORIES_SUCCESS'
export const FETCH_SUBJECT_CATEGORIES_FAILURE =  'FETCH_SUBJECT_CATEGORIES_FAILURE'

export const POST_SUBJECT_CATEGORY_REQUEST =    'POST_SUBJECT_CATEGORY_REQUEST'
export const POST_SUBJECT_CATEGORY_SUCCESS =    'POST_SUBJECT_CATEGORY_SUCCESS'
export const POST_SUBJECT_CATEGORY_FAILURE =    'POST_SUBJECT_CATEGORY_FAILURE'

export const UPDATE_SUBJECT_CATEGORY_REQUEST =  'UPDATE_SUBJECT_CATEGORY_REQUEST'
export const UPDATE_SUBJECT_CATEGORY_SUCCESS =  'UPDATE_SUBJECT_CATEGORY_SUCCESS'
export const UPDATE_SUBJECT_CATEGORY_FAILURE =  'UPDATE_SUBJECT_CATEGORY_FAILURE'

export const EDIT_SUBJECT_CATEGORY = 'EDIT_SUBJECT_CATEGORY'
export const SUBJECT_CATEGORY_INFO = 'SUBJECT_CATEGORY_INFO'

export const REMOVE_SUBJECT_CATEGORY_REQUEST = 'REMOVE_SUBJECT_CATEGORY_REQUEST'
export const REMOVE_SUBJECT_CATEGORY_SUCCESS = 'REMOVE_SUBJECT_CATEGORY_SUCCESS'
export const REMOVE_SUBJECT_CATEGORY_FAILURE = 'REMOVE_SUBJECT_CATEGORY_FAILURE'

