export const FETCH_SHIFTS_REQUEST = 'FETCH_SHIFTS_REQUEST'
export const FETCH_SHIFTS_SUCCESS = 'FETCH_SHIFTS_SUCCESS'
export const FETCH_SHIFTS_FAILURE = 'FETCH_SHIFTS_FAILURE'

export const POST_SHIFT_REQUEST = 'POST_SHIFT_REQUEST'
export const POST_SHIFT_SUCCESS = 'POST_SHIFT_SUCCESS'
export const POST_SHIFT_FAILURE = 'POST_SHIFT_FAILURE'

export const UPDATE_SHIFT_REQUEST = 'UPDATE_SHIFT_REQUEST'
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS'
export const UPDATE_SHIFT_FAILURE = 'UPDATE_SHIFT_FAILURE'

export const EDIT_SHIFT = 'EDIT_SHIFT'
export const SHIFT_INFO = 'SHIFT_INFO'

export const REMOVE_SHIFT_REQUEST = 'REMOVE_SHIFT_REQUEST'
export const REMOVE_SHIFT_SUCCESS = 'REMOVE_SHIFT_SUCCESS'
export const REMOVE_SHIFT_FAILURE = 'REMOVE_SHIFT_FAILURE'

