    json.(
            @user, 
                :id, 
                :username, 
                :password, 
                :email,
                :role,
                :created_at, 
                :updated_at
        )
