export const FETCH_APPLICANTS_REQUEST = 'FETCH_APPLICANTS_REQUEST'
export const FETCH_APPLICANTS_SUCCESS = 'FETCH_APPLICANTS_SUCCESS'
export const FETCH_APPLICANTS_FAILURE = 'FETCH_APPLICANTS_FAILURE'

export const FETCH_SEARCH_APPLICANTS_REQUEST = 'FETCH_SEARCH_APPLICANTS_REQUEST'
export const FETCH_SEARCH_APPLICANTS_SUCCESS = 'FETCH_SEARCH_APPLICANTS_SUCCESS'
export const FETCH_SEARCH_APPLICANTS_FAILURE = 'FETCH_SEARCH_APPLICANTS_FAILURE'

export const POST_APPLICANT_REQUEST = 'POST_APPLICANT_REQUEST'
export const POST_APPLICANT_SUCCESS = 'POST_APPLICANT_SUCCESS'
export const POST_APPLICANT_FAILURE = 'POST_APPLICANT_FAILURE'

export const UPDATE_APPLICANT_REQUEST = 'UPDATE_APPLICANT_REQUEST'
export const UPDATE_APPLICANT_SUCCESS = 'UPDATE_APPLICANT_SUCCESS'
export const UPDATE_APPLICANT_FAILURE = 'UPDATE_APPLICANT_FAILURE'

export const EDIT_APPLICANT = 'EDIT_APPLICANT'
export const APPLICANT_INFO = 'APPLICANT_INFO'
export const EMPTY_APPLICANTS = 'EMPTY_APPLICANTS'

export const REMOVE_APPLICANT_REQUEST = 'REMOVE_APPLICANT_REQUEST'
export const REMOVE_APPLICANT_SUCCESS = 'REMOVE_APPLICANT_SUCCESS'
export const REMOVE_APPLICANT_FAILURE = 'REMOVE_APPLICANT_FAILURE'

