json.(
    @applicant, 
        :id, 
        :first_name,
        :last_name,
        :patronymic,
        :age,
        :home_phone,
        :mobile_phone,
        :school_grade,
        :notes, 
        :created_at, 
        :updated_at,
        :user_id
)