export const FETCH_RESERVATIONS_REQUEST =  'FETCH_RESERVATIONS_REQUEST'
export const FETCH_RESERVATIONS_SUCCESS =  'FETCH_RESERVATIONS_SUCCESS'
export const FETCH_RESERVATIONS_FAILURE =  'FETCH_RESERVATIONS_FAILURE'

export const POST_RESERVATION_REQUEST =    'POST_RESERVATION_REQUEST'
export const POST_RESERVATION_SUCCESS =    'POST_RESERVATION_SUCCESS'
export const POST_RESERVATION_FAILURE =    'POST_RESERVATION_FAILURE'

export const UPDATE_RESERVATION_REQUEST =  'UPDATE_RESERVATION_REQUEST'
export const UPDATE_RESERVATION_SUCCESS =  'UPDATE_RESERVATION_SUCCESS'
export const UPDATE_RESERVATION_FAILURE =  'UPDATE_RESERVATION_FAILURE'

export const EDIT_RESERVATION = 'EDIT_RESERVATION'
export const RESERVATION_INFO = 'RESERVATION_INFO'

export const REMOVE_RESERVATION_REQUEST = 'REMOVE_RESERVATION_REQUEST'
export const REMOVE_RESERVATION_SUCCESS = 'REMOVE_RESERVATION_SUCCESS'
export const REMOVE_RESERVATION_FAILURE = 'REMOVE_RESERVATION_FAILURE'

