json.(
    @reservation, 
        :id, 
        :applicant_id,
        :season_id,
        :shift_id,
        :subject_id,
        :is_registered,
        :is_sms_sent,
        :is_called,
        :notes, 
        :created_at, 
        :updated_at,
)