export const FETCH_SEASONS_REQUEST = 'FETCH_SEASONS_REQUEST'
export const FETCH_SEASONS_SUCCESS = 'FETCH_SEASONS_SUCCESS'
export const FETCH_SEASONS_FAILURE = 'FETCH_SEASONS_FAILURE'

export const POST_SEASON_REQUEST = 'POST_SEASON_REQUEST'
export const POST_SEASON_SUCCESS = 'POST_SEASON_SUCCESS'
export const POST_SEASON_FAILURE = 'POST_SEASON_FAILURE'

export const UPDATE_SEASON_REQUEST = 'UPDATE_SEASON_REQUEST'
export const UPDATE_SEASON_SUCCESS = 'UPDATE_SEASON_SUCCESS'
export const UPDATE_SEASON_FAILURE = 'UPDATE_SEASON_FAILURE'

export const EDIT_SEASON = 'EDIT_SEASON'
export const SEASON_INFO = 'SEASON_INFO'

export const REMOVE_SEASON_REQUEST = 'REMOVE_SEASON_REQUEST'
export const REMOVE_SEASON_SUCCESS = 'REMOVE_SEASON_SUCCESS'
export const REMOVE_SEASON_FAILURE = 'REMOVE_SEASON_FAILURE'

